### ISSUE TITLE
3x-ui panel with docker only listen ipv6:2053

### ISSUE THREAD

**Issue by leic4u** [MHSanaei/3x-ui#1209]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

I install 3x-ui panel with docker compose, it's my docker-compose.yml:
```
version: '3.3'
services:
    3x-ui:
        stdin_open: true
        tty: true
        environment:
            - XRAY_VMESS_AEAD_FORCED=false
        volumes:
            - './db/:/etc/x-ui/'
            - './cert/:/root/cert/'
        network_mode: host
        restart: unless-stopped
        container_name: 3x-ui
        image: 'ghcr.io/mhsanaei/3x-ui:latest'
```

I can't access 3x-ui panel with ipv4:2053, while my vps does not have ipv6, so I disconnected with the 3x-ui panel.

### Version of 3x-ui

<details>

```console
Server ready
2023/11/09 17:24:08 x-ui 1.7.9
2023/11/09 17:24:08 INFO - web server run http on [::]:2053
```

</details>

### x-ui log reports or xray log

<details>

```console
Server ready
2023/11/09 17:24:08 x-ui 1.7.9
2023/11/09 17:24:08 INFO - web server run http on [::]:2053
```

</details>

**Comment by mezhgano** [comment]
Thanks for the info, but how do you solve this?

**Comment by mezhgano** [comment]
I don't know if this correct way, but i solve this by changing `docker-compose` line from:

`network_mode: host`

to:

```
ports:
     - target: 2053
        published: 2053
        protocol: tcp
        mode: host
```
