### ISSUE TITLE
k3s implementation

### ISSUE THREAD

**Issue by kazemmdev** [MHSanaei/3x-ui#1761]
Hello everyone,

First off, I want to express my deep appreciation for this fantastic panel; its design is truly appealing. I've been working on deploying this panel using Kubernetes and have followed the configuration detailed below. So far, the deployment seems successful—I can access the panel dashboard, and everything appears to be functioning correctly. I've even managed to create a bond. However, I'm encountering an issue where this bond isn't accessible, despite confirming that the necessary ports are open. Could anyone offer any advice or tips on this matter?

Here's the Kubernetes configuration I used:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-ui
  labels:
    app.kubernetes.io/name: xui
    app.kubernetes.io/tier: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: xui
      app.kubernetes.io/tier: proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: xui
        app.kubernetes.io/tier: proxy
    spec:
      containers:
      - name: x-ui
        image: ghcr.io/mhsanaei/3x-ui:latest
        env:
        - name: XRAY_VMESS_AEAD_FORCED
          value: "false"
        volumeMounts:
        - name: db-volume
          mountPath: /etc/x-ui/
        - name: cert-volume
          mountPath: /root/cert/
        tty: true
      volumes:
      - name: db-volume
        hostPath:
          path: /root/xui/db/
      - name: cert-volume
        hostPath:
          path: /root/xui/cert/
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: x-ui-srv
spec:
  selector:
    app.kubernetes.io/name: xui
    app.kubernetes.io/tier: proxy
  type: LoadBalancer
  ports:
  - name: web-interface
    port: 2053
    targetPort: 2053
  - name: secure-api
    port: 8443
    targetPort: 8443

```
