### ISSUE TITLE
How to configure ssl if 3x-ui is used in docker container? 

### ISSUE THREAD

**Issue by wedcanto** [MHSanaei/3x-ui#2166]
I ran the commands 

```
apt-get install certbot -y
certbot certonly --standalone --agree-tos --register-unsafely-without-email -d mydomain.com
certbot renew --dry-run
```

Successfully got the certificates, they are stored in the 
```
 /etc/letsencrypt/live/mydomain.com/fullchain.pem
/etc/letsencrypt/live/mydomain.com/privkey.pem
```

I tried changing the docker-compose.yaml to this one:

```
version: "3"

services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    hostname: yourhostname
    volumes:
      - /etc/letsencrypt/live/mydomain.com/fullchain.pem:/root/cert/fullchain.pem:ro
      - /etc/letsencrypt/live/mydomain.com/privkey.pem:/root/cert/privkey.pem:ro
      - ./db/:/etc/x-ui/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped
```
    
   But I still have error -   **SSL_ERROR_RX_RECORD_TOO_LONG**
