### ISSUE TITLE
The subscription service gives two ports for VLESS: `vless://123abc@my.example.com:12121:443?flow=...`

### ISSUE THREAD

**Issue by voronin9032** [MHSanaei/3x-ui#2470]
**Describe the bug**
The subscription service gives two ports (12121 and 443) for VLESS: `vless://123abc...@my.example.com:12121:443?flow=...` when the service is behind a reverse proxy that runs TLS on a non-standard port (12121). It doesn't work, cannot connect, have to remove the extra port manually: `vless://123abc...@my.example.com:443?flow=...`.

**Expected behavior**
Running  `curl --silent 'https://my.example.com:12121/mysecretpath/sub/myclient_shmcxfe5621fjzbq' | base64 --decode` should print a URL with only one (correct) port: `vless://123abc...@my.example.com:443?flow=...`

**Screenshots**

**Version (please complete the following information):**
 - 3X-UI Version: 2.3.12
 - Xray Version: 1.8.23

**Additional context**
`docker-compose.yml`:
```yaml
services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    hostname: wg.ag02.ru
    volumes:
      - ./3x-ui/db/:/etc/x-ui/
      - ./3x-ui/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped
  caddy:
    image: caddy:2.8-alpine
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
```

`Caddyfile`:
```
{
        email myemail@example.com
}

https://my.example.com:12121 {
        reverse_proxy localhost:2096
}
```

3x-ui configuration:
![image](https://github.com/user-attachments/assets/7a603eb4-c401-47b9-b4ce-85e0110d73c8)
![image](https://github.com/user-attachments/assets/ab02b4d9-a69c-4a9a-ab91-7f4e4e92d2e7)
![image](https://github.com/user-attachments/assets/db9f8ff7-b57c-4840-a04e-70ae25c556d6)
![image](https://github.com/user-attachments/assets/8042279d-4470-44ff-ab98-953cd152fd2c)
![image](https://github.com/user-attachments/assets/1217fbf1-163c-42e3-a526-3c8318668ca3)
![image](https://github.com/user-attachments/assets/6f3209f6-69a7-4745-ad36-a3b01f40ac84)
![image](https://github.com/user-attachments/assets/86698609-0006-42f8-8cb0-eb5bc8f3e660)
![image](https://github.com/user-attachments/assets/0e2a035a-0e5b-4541-ae73-b645c1909c81)
![image](https://github.com/user-attachments/assets/272a88be-ad5b-4657-853e-3751b322b918)

The 3x-ui panel and the subscription service listen only to localhost. An SSH tunnel is used to reach the panel. A Caddy instance reverse proxies `https://my.example.com:12121` to the subscription service `localhost:2096`. I didn't edit Xray Configs in the panel manually.
