### ISSUE TITLE
Setting up domain access to get no front-end resources

### ISSUE THREAD

**Issue by chienxx** [MHSanaei/3x-ui#2800]
After setting up the basepath and using the caddy reverse proxy, I can see that the proxy is successful through the domain name, but the loading of static files fails.

<img width="398" alt="Image" src="https://github.com/user-attachments/assets/19b67cf4-0fcd-44ba-9826-49d3581b3ffe" />

**Comment by shishkevichd** [comment]
Hello.

Hi. I tried to raise 3xui+ Caddy, but did not encounter a problem.

Here is my configuration:

<details><summary>compose.yml</summary>
<p>

```yaml
services:
  3xui:
    container_name: vpn_app
    volumes:
      - ~/vpn/data/3xui/db/:/etc/x-ui/
      - ~/vpn/data/3xui/cert/:/root/cert
    tty: true
    restart: unless-stopped
    networks:
      - vpn
    image: ghcr.io/mhsanaei/3x-ui:latest
  caddy:
    container_name: vpn_proxy
    restart: unless-stopped
    networks:
      - vpn
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/vpn/data/caddy/Caddyfile:/etc/caddy/Caddyfile
    image: caddy:latest

networks:
  vpn:
```

</p>
</details> 

<details><summary>Caddyfile</summary>
<p>

```caddyfile
vpn.example.com {
        reverse_proxy vpn_app:2053
}
```

</p>
</details> 

<details><summary>Screenshots</summary>
<p>

![Image](https://github.com/user-attachments/assets/6ef65f44-4890-4dce-a3c4-2a256e3d3893)

</p>
</details>
