### ISSUE TITLE
proxy network error

### ISSUE THREAD

**Issue by chienxx** [MHSanaei/3x-ui#2816]
Running the panel in bridge mode, an inbound rule is configured, and the inbound port of the firewall is open,but the ERROR is prompted during the clash test. 

But the same inbound rule config works fine on another machine(panel install by script).My compose.yml config is:
```yml
services:
  3xui:
    container_name: 3xui
    volumes:
      - ./data/3xui/db/:/etc/x-ui/
      - ./data/3xui/cert/:/root/cert
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      X_UI_ENABLE_FAIL2BAN: "true"
    tty: true
    restart: unless-stopped
    networks:
      - vpn
    image: ghcr.io/mhsanaei/3x-ui:latest
  caddy:
    container_name: caddy
    restart: unless-stopped
    networks:
      - vpn
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/caddy/Caddyfile:/etc/caddy/Caddyfile
    image: caddy:latest

networks:
  vpn:
    external: true
```
