### ISSUE TITLE
Can't run the panel in a container

### ISSUE THREAD

**Issue by xxyk** [MHSanaei/3x-ui#2894]
**Describe the bug**
Can't run it in a docker.
I'm using ubuntu 20.04, and the version of glibc is 2.31. So I tried to run 3x-ui using docker. However, this container uses alpine and the installer can't recognize the version of glibc, and it failed.

**Screenshots**

![Image](https://github.com/user-attachments/assets/e533f01a-cb28-4c79-94eb-121e9b86eba7)

**Version (please complete the following information):**
 - 3X-UI Version : 2.5.7

**Comment by shishkevichd** [comment]
Hello!

I have not been able to replicate this problem, I have it starting up and working fine.

![Image](https://github.com/user-attachments/assets/e33ffbce-3824-4430-af49-e600493988dd)

Used configuration:

```yaml
services:
    3x-ui:
        stdin_open: true
        tty: true
        environment:
            - XRAY_VMESS_AEAD_FORCED=false
        volumes:
            - ~/vpn/data/db/:/etc/x-ui/
            - ~/vpn/data/cert/:/root/cert/
        network_mode: host
        restart: unless-stopped
        container_name: 3xui_app
        image: ghcr.io/mhsanaei/3x-ui:latest
```
